majority_report/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('majority_report_app.urls'))
]

majority_report_app/urls.py
#Defines URL patterns for majority_report_apps

from django.urls import path

from . import views

app_name = 'majority_report_app'
urlpatterns = [
    #Home Page
    path('',views.index, name = "index"),
    #Enviornment Form Page
    path('enviornment_variables/', views.env_forms, name = "variables"),
    path('results/<int:env_id>/', views.results, name = "results"),
    
]

majority_report_app/models.py
from django.db import models

import car_variables.choices as cv

# Create your models here.

class Enviornment(models.Model):
    #One-Time Variables
    distance = models.IntegerField("Distance:", default = 1000)
    car1_spd = models.IntegerField("Vehicle 1 Speed:", default = 70)
    car2_spd = models.IntegerField("Vehicle 2 Speed:", default = 70)
    road_width = models.IntegerField("Road Width:", default = 3)
    weather = models.IntegerField("Weather:", choices = cv.WEATHER_CHOICES, default = 0)
    time = models.IntegerField("Time:", choices = cv.TIME_CHOICES, default = 0)
    road_type = models.IntegerField("Road Type:", choices = cv.ROAD_CHOICES, default = 0)
    driver_exp1 = models.IntegerField("Driver 1 Experience:", choices = cv.DRIVER_EXP_CHOICES, default = 0)
    driver_exp2 = models.IntegerField("Driver 2 Experience:", choices = cv.DRIVER_EXP_CHOICES, default = 0)
    driver_dui1 = models.IntegerField("Driver 1 Chemical Influence:", choices = cv.DRIVER_DUI_CHOICES, default = 0)
    driver_dui2 = models.IntegerField("Driver 2 Chemical Influence:", choices = cv.DRIVER_DUI_CHOICES, default = 0)
    driver_vision1 = models.IntegerField("Driver 1 Vision:", choices = cv.DRIVER_VISION_CHOICES, default = 0)
    driver_vision2 = models.IntegerField("Driver 2 Vision:", choices = cv.DRIVER_VISION_CHOICES, default = 0)
    driver_age1 = models.IntegerField("Driver 1 Age:", choices = cv.DRIVER_AGE_CHOICES, default = 0)
    driver_age2 = models.IntegerField("Driver 2 Age:", choices = cv.DRIVER_AGE_CHOICES, default = 0)
    vehicle1 = models.IntegerField("Vehicle 1 Type:", choices = cv.VEHICLE_CHOICES, default = 0)
    vehicle2 = models.IntegerField("Vehicle 2 Type:", choices = cv.VEHICLE_CHOICES, default = 0)
    computer = models.IntegerField("AI Computer:", choices = cv.COMPUTER_CHOICES, default = 0)
    
class Drive(models.Model):
    #Repeating Variables
    env = models.ForeignKey(Enviornment, on_delete=models.CASCADE)
    car1_prog = models.DecimalField("Vehicle 1 Progress:", max_digits=999, decimal_places=2, default = 0)
    ghost_prog = models.DecimalField("AI Ghost Progress:", max_digits=999, decimal_places=2, default = 0)
    car2_prog = models.DecimalField("Vehicle 2 Progress:", max_digits=999, decimal_places=2, default = 0)
    car1_turndist = models.DecimalField("Vehicle 1 Turn Distance:", max_digits=999, decimal_places=2, default = 0)
    ghost_turndist = models.DecimalField("AI Ghost Turn Distance:", max_digits=999, decimal_places=2, default = 0)
    car2_turndist = models.DecimalField("Vehicle 2 Turn Distance:", max_digits=999, decimal_places=2, default = 0)
    outcome = models.CharField("Outcome:", max_length = 120, default = "")
    accuracy = models.IntegerField("Accuracy:", default = 0)

majority_report_app/forms.py
from django import forms

from .models import Enviornment

class EnviornmentForm(forms.ModelForm):
    class Meta:
        model = Enviornment
        fields = ['distance','car1_spd','car2_spd','road_width','weather','time','road_type','driver_exp1','driver_exp2','driver_dui1','driver_dui2',
                  'driver_vision1','driver_vision2','driver_age1','driver_age2','vehicle1','vehicle2','computer']
        labels = {'distance':'Distance (Meters)',
                  'car1_spd':'Vehicle 1 Speed (MPH)',
                  'car2_spd':'Vehicle 2 Speed (MPH)',
                  'driver1_exp':'Driver 1 Experience',
                  'driver2_exp':'Driver 2 Experience',
                  'driver1_dui':'Driver 1 Chemical Influence',
                  'driver2_dui':'Driver 2 Chemical Influence',
                  'driver1_vision':'Driver 1 Vision',
                  'driver2_vision':'Driver 2 Vision',
                  'driver1_age':'Driver 1 Age',
                  'driver2_age':'Driver 2 Age',
                  'vehicle1':'Vehicle 1 Type',
                  'vehicle2':'Vehicle 2 Type',
                  'computer':'AI Computer',
                  }

majority_report_app/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse

from .models import Enviornment,Drive
from .forms import EnviornmentForm

from car_sim.views import Car, maj_intro, sim_collision, AI
from car_variables.views import Mods,modifiers_intro

def index(request):
    context = {}
    # The Majority Report homepage
    return render(request, 'majority_report_app/index.html', context)

def env_forms(request):
    #Variable Select Page
    if request.method != 'POST':
        form = EnviornmentForm
    else:
        form = EnviornmentForm(data=request.POST)
        if form.is_valid():
            env = form.save()
            return HttpResponseRedirect(reverse('majority_report_app:results', args = [env.id]))
        
    context = {'form': form}
    return render(request, 'majority_report_app/enviornment_variables.html', context)

def results(request,env_id):
    #Return all Variables
    env = Enviornment.objects.get(id=env_id)
    mods = modifiers_intro(env)
    car1 = Car("Car 1",0)
    car2 = Car("Car 2",0)
    Skynet = AI(mods.modify_data["computer"][mods.modify_choices["computer"]]["name"],mods.modify_data["computer"][mods.modify_choices["computer"]]["comp_power"])
    maj_intro(car1,car2,env)
    sim_collision(car1,car2,Skynet,mods,env)
    context = {'var': env}
    return render(request, 'majority_report_app/results.html', context)

majority_report_app/templates/majority_report_app/base.html
<p>
    <a href="{% url 'majority_report_app:index' %}">Majority Report</a>
<p>

{% block content %}{% endblock content %}

majority_report_app/templates/majority_report_app/enviornment_variables.html
{% extends "majority_report_app/base.html" %}

{% block content %}

    <p>Select Simulation Conditions:</p>
    <form action="{% url 'majority_report_app:variables' %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name = "submit">Run Simulation</button>
    </form>

{% endblock content %}

majority_report_app/templates/majority_report_app/index.html
{% extends "majority_report_app/base.html" %}

{% block content %}
    <a href="{% url 'majority_report_app:variables' %}">Start a New Run</a>
{% endblock content %}

majority_report_app/templates/majority_report_app/results.html
{% extends 'majority_report_app/base.html' %}

{% block content %}

<p>Distance: {{var.distance}}m</p>
<p>Vehicle 1 Speed: {{var.car1_spd}} MPH</p>
<p>Vehicle 2 Speed: {{var.car2_spd}} MPH</p>
<p>Road Width: {{var.road_width}}</p>
<p>Weather: {{var.weather}}</p>
<p>Time: {{var.time}}</p>
<p>Road Type: {{var.road_type}}</p>
<p>Driver 1 Experience: {{var.driver_exp1}}</p>
<p>Driver 2 Experience: {{var.driver_exp2}}</p>
<p>Driver 1 Chemical Influence: {{var.driver_dui1}}</p>
<p>Driver 2 Chemical Influence: {{var.driver_dui2}}</p>
<p>Driver 1 Vision: {{var.driver_vision1}}</p>
<p>Driver 2 Vision: {{var.driver_vision2}}</p>
<p>Driver 1 Age: {{var.driver_age1}}</p>
<p>Driver 2 Age: {{var.driver_age2}}</p>
<p>Vehicle 1 Type: {{var.vehicle1}}</p>
<p>Vehicle 2 Type: {{var.vehicle2}}</p>
<p>AI Computer: {{var.computer}}</p>

{% endblock content%}